version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: awesomehub
      POSTGRES_USER: awesomehub
      POSTGRES_PASSWORD: awesomehub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awesomehub -d awesomehub"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: